# Generated by Django 3.2.7 on 2021-09-17 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='human',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
